name: "ðŸ› Bug Report"
description: "Something isn't working as expected"
title: "[Bug] "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug!

        âš ï¸ Please note: the `main` branch is **development-only** and may not compile outside this repo.
        For application usage, please depend on a **tagged release** from Hex.pm.

  - type: input
    id: elixir_version
    attributes:
      label: "Elixir & OTP versions"
      placeholder: "Elixir 1.18.3, OTP 27"
    validations:
      required: true

  - type: input
    id: lotus_versions
    attributes:
      label: "Lotus & LotusWeb versions"
      description: "Paste the relevant dependency lines from your `mix.exs`"
      placeholder: '{:lotus, "~> 0.9.2"}, {:lotus_web, "~> 0.6.0"}'
    validations:
      required: true

  - type: input
    id: phoenix_version
    attributes:
      label: "Phoenix version"
      description: "From `mix.exs` or `mix hex.info phoenix`"
      placeholder: "phoenix 1.7.12"
    validations:
      required: true

  - type: input
    id: live_view_version
    attributes:
      label: "Phoenix LiveView version"
      description: "From `mix.exs` or `mix hex.info phoenix_live_view`"
      placeholder: "phoenix_live_view 1.0.0"
    validations:
      required: true

  - type: input
    id: phoenix_html_template_versions
    attributes:
      label: "Phoenix.HTML / Phoenix.Template versions"
      description: "If present in your project"
      placeholder: "phoenix_html 4.1.0, phoenix_template 1.0.4"

  - type: input
    id: phoenix_js_packages
    attributes:
      label: "Phoenix JS packages (assets)"
      description: "From `assets/package.json` if applicable"
      placeholder: '"phoenix": "~1.7.x", "phoenix_html": "~4.x", "phoenix_live_view": "~1.0.x"'

  - type: input
    id: os_browser
    attributes:
      label: "OS and Browser"
      description: "For UI/UX or rendering issues"
      placeholder: "macOS 14.6.1, Chrome 128.0.0"

  - type: input
    id: node_pkg_manager
    attributes:
      label: "Node.js & package manager"
      description: "If assets build or LiveView JS behavior is involved"
      placeholder: "Node 20.11.0, npm 10.2.0"

  - type: input
    id: db_adapter
    attributes:
      label: "Database & adapter (optional)"
      description: "If query execution or variable binding matters"
      placeholder: "PostgreSQL 16, Ecto 3.11, postgrex 0.17"

  - type: textarea
    id: steps
    attributes:
      label: "Steps to reproduce"
      description: "Exact steps and commands to reproduce the issue"
      placeholder: |
        1. mix deps.get
        2. mix ecto.gen.migration create_lotus_tables
        3. Start server and navigate to /lotus
        4. ...
    validations:
      required: true

  - type: textarea
    id: minimal_repro
    attributes:
      label: "Minimal repro code / snippet"
      description: "A LiveView/HEEx snippet or link to a minimal repo, if possible"
      placeholder: "Paste the smallest snippet that reproduces the problem"

  - type: textarea
    id: expected
    attributes:
      label: "What did you expect to happen?"
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: "What actually happened?"
      description: "Paste the full error message / stacktrace"
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: "Screenshots / screen recording (optional)"
      description: "Drag and drop images or GIFs if helpful"

  - type: checkboxes
    id: confirmations
    attributes:
      label: "Confirm"
      options:
        - label: "I am using a **tagged release**, not the `main` branch."
          required: true
        - label: "I searched existing issues and discussions for this problem."
          required: true
